version: "3.9"

networks:
  default:
    driver: ${NETWORKS_DRIVER}
  nestjs-app-network:
    external: true
  common-net:
    external: true

services:
  nestjs_app_basic_dev:
    command: ["yarn", "run", "start"]
    ports:
      - ${BACKEND_NESTJS_APP_PUBLISH_HTTP_PORT}:3000
    volumes:
      - ${DOCKER_BUILD_BACKEND_CONTEXT_DIR}/nestjs_app_basic:/app
      - nestjs-app-basic-node-modules:/app/node_modules
    networks:
      default:
      common-net:
        aliases:
          - common-nestjs-app-basic-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nestjs_app_https_support:
    ports:
      - ${BACKEND_NESTJS_APP_PUBLISH_HTTPS_PORT}:3000
    volumes:
      - ${DOCKER_BUILD_BACKEND_CONTEXT_DIR}/nestjs_app_https_support:/app
      - nestjs-app-https-support-node-modules:/app/node_modules
    networks:
      default:
      common-net:
        aliases:
          - common-nestjs-app-https-support-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nestjs_app_modules:
    ports:
      - ${BACKEND_NESTJS_APP_MODULES_PUBLISH_PORT}:3000
    volumes:
      - ${DOCKER_BUILD_BACKEND_CONTEXT_DIR}/nestjs_app_modules:/app
      - nestjs-app-modules-node-modules:/app/node_modules
    networks:
      default:
      common-net:
        aliases:
          - common-nestjs-app-modules-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
